[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ["py38", "py39", "py310", "py311", "py312"]

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 79
